### ISSUE TITLE
Request for Textpattern-styled CSS for server holding pages

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-branding#4]
https://github.com/textpattern/server-config/issues/51

Pinging @philwareham - is there a production-ready CSS file I can snag for a holding page when Textpattern server sites are being auto-rebuilt to a schedule, please? Would like to phase out current Tachyons framework if feasible. Thank you.

**Comment by philwareham** [comment]
Can you screen grab an example of the holding page. I can then provide a minimal CSS file to be served. Ta!

**Comment by petecooper** [comment]
Apologies @philwareham - I may be wrong, can't find the holding page anywhere…I may have already designed it out. I'll close this, and open again if the need arises. Sorry!
